---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: url-shortener-secrets
  namespace: url-shortener
spec:
  encryptedData:
    database-url: AgCbX/K6WjKQ6TYKXVLjSrdxvRdzRl9GGlrfN1m9vzg8nzEbPPBhHCn3SgWyczPY6rfIDwrRIQG0h+DK0OgKbL9W0EHqzIjc08FzSoXUnBM/1Lx0yR8HPiOf9ZV6rqxD4+Qz1xuuWAmiZhJ0ebidc5Z8F91WowwIUMBGat7SAQNwVw3UvPWwt3s6UUwqruehINKdPJyx3nbnn4cAP2GdZZNmrD18YhCpuJwhm85a+oAHZ/YH+J7foaozxoFat+koVxalSZl3hChlLCGmA4gCKAIin70mlZER0hOpZ/1bnQ4EAq/X4VKWTPE2BHwNOF3sqeeGmJNjiEAf4mT9+qTFEZhoKAeoJAive8X6CJRKv2r//YSg1dUNn8bpcS414zsK6R9caXwOgLHdd7mThpA0AliT6SekkorqOJsRa+HhN97jIuu0Q4blmXnBnE+CfkFDNge1diXmhpFSjR9TUQ+335feum3YqAK6teniTMW4OHf5kJ7P+02dEzzkghjjdPHNG/Gm82lr3LwBwk5ybkLnS2aqYsnCo4+rsyDK6b9tfLPnwcNqFxTHB3zcGivA2/XF+3ft3i4Yi8apbd/S/snF8nFfdbGCI94mLQtd6kgzDBJ1T7ywx+2B5zjp0lEvBq+3b1sqD9zVvEoU/8/GV2OHhCjHtBNVsA9TSp4PtDqAouu8kWGMYcg5f9zW5NidBHp0dx03VoKcMA610meAKtvKTap2JBgZz5CLdgRrhWOkpV2/Bpw6l91E5G41KONkBvcCzYLv
    postgres-password: AgBNb9oLV2KiWcMDOOgmaDRWQL43Zn4gAFxQ7ZO1c3L9tavB5OVy45dYDyBTk4ULGEWK5wfEEq35OTv5FZMGfllx0ONDLNmpdly3YhP/732ppdreaDN684OtIU47WPaDq4FwgXqDdT6vTC4qgugUMfAB7ZVGw4NUKk6qqKancDO/Q9O9PTgEqe86hBC3tz0y+AVCgQgsJ1VXOe8E4w92O3pPcxLnG5vhtH7KgQ0tVcduICEaJHkQ1lVrmCGP2S/moEnDIL3H2GrkwHKyPgoPSkp1SiwweIfe2DYf/yhkGtGN172Xb4eq8ouJ94Z1OSiaD5cO/GvpVguCyhXx81vpp0hOCEKMInViZIQSygWBBcomxxaUPfsiuVBI0ZMQAI8pdr0rbDUz2JVZ5IoWa1DomjuHLouLxf+EbBjG5yfBjvwAdGyRnrmskxoAWRbqgY+hgCQ+bmPgqdqdvtmpx8Rdc8+iIVHHNSmx5XrwwOlQkenmPX8uI9dvLI7/dZ0ssT9CwXSh0Dp81u1qWaxiiqxM1ZG6j1oLTSCDRpjP6Xv008hb+z51vm598ZH2l//HX4NH7gO90z3ovJBQkjX4FMzpomkbVvXpGjFYRWoDr203AojPD0Az109GGNUPsaUnfkdwmdc5Scg4vN05//cCRQYmxxdun0NW4CAub/7BpK9L3NW2TsyPw3UUs0jtpw8xP1RXOrfDlbSg8w==
  template:
    metadata:
      name: url-shortener-secrets
      namespace: url-shortener
    type: Opaque
