apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secrets
  namespace: url-shortener
type: Opaque
stringData:
  database-url: "postgres://app:12345@postgresql:5432/urlshortener"
  postgres-password: "12345"
